spring:
  application:
    name: serve
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bs?serverTimezone=UTC&useSSL=false
    username: root
    password: woalzm13.

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
      file-size-threshold: 0

  # Redis配置
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 5000
      # 如果有密码请取消注释并设置密码
      # password: yourpassword

  # Jackson配置
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8
  
  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 465
    username: ljq2336856534@qq.com
    password: cbywpsrqkseqecda
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
    
  # 文件上传配置
  upload:
    # 学生照片保存路径（使用绝对路径）
    photo-path: D:/Users/Merri/Desktop/graduate/uploads/student-photos
    # 照片访问URL前缀（如果需要通过网络访问）
    photo-url-prefix: /uploads/student-photos

# 服务器配置
server:
  port: 8080

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.serve.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl